import type { Listing, AvailabilityBlock } from "./types";

export const mockListings: Listing[] = [
  {
    id: "1",
    hostId: "host_1",
    createdAt: "2026-01-10T10:00:00Z",
    title: "Cochera cubierta en Palermo Soho",
    description:
      "Cochera cubierta y segura en pleno corazón de Palermo Soho. Ideal para autos medianos y grandes. Acceso 24/7 con portón automático. A pasos de Plaza Serrano y principales avenidas. Perfecto para quienes buscan estacionar cerca de bares, restaurantes y oficinas.",
    spaceType: "Cochera",
    areaLabel: "Palermo Soho, CABA",
    approxLatLng: { lat: -34.5881, lng: -58.4263 },
    fullAddressPrivate: "Gorriti 4567, CABA",
    sizeM2: 12,
    fits: ["Auto", "SUV"],
    accessType: "24_7",
    rulesAllowed: [
      "Estacionamiento las 24 horas",
      "Vehículos particulares",
      "Motocicletas",
    ],
    rulesNotAllowed: [
      "Vehículos comerciales grandes",
      "Trabajos de mecánica",
      "Lavado de autos",
    ],
    amenities: [
      "Portón automático",
      "Cámaras de seguridad",
      "Iluminación LED",
      "Vigilancia",
    ],
    priceDaily: 2500,
    priceWeekly: 15000,
    priceMonthly: 50000,
    photos: [],
    status: "active",
  },
  {
    id: "2",
    hostId: "host_1",
    createdAt: "2026-01-12T14:30:00Z",
    title: "Baulera amplia en Recoleta",
    description:
      "Baulera de 8m² en edificio premium de Recoleta. Segura, seca y ventilada. Ideal para guardar muebles, cajas, equipamiento deportivo y más. Edificio con seguridad 24hs. Acceso en horarios acordados con el encargado.",
    spaceType: "Baulera",
    areaLabel: "Recoleta, CABA",
    approxLatLng: { lat: -34.5889, lng: -58.3936 },
    fullAddressPrivate: "Junín 1234, CABA",
    sizeM2: 8,
    fits: ["Muebles", "Cajas", "Bicicletas", "Equipamiento deportivo"],
    accessType: "scheduled",
    accessHoursText: "Lun-Vie 9-20hs, Sáb 10-14hs",
    rulesAllowed: [
      "Muebles y electrodomésticos",
      "Cajas selladas",
      "Objetos personales",
    ],
    rulesNotAllowed: [
      "Alimentos perecederos",
      "Productos químicos",
      "Materiales inflamables",
    ],
    amenities: ["Seguridad 24hs", "Seco y ventilado", "Candado incluido"],
    priceDaily: 800,
    priceWeekly: 4500,
    priceMonthly: 15000,
    photos: [],
    status: "active",
  },
  {
    id: "3",
    hostId: "host_2",
    createdAt: "2026-01-15T09:15:00Z",
    title: "Depósito comercial en Villa Crespo",
    description:
      "Depósito de 25m² perfecto para emprendedores y pequeños comercios. Altura suficiente para estanterías. Acceso con camioneta o utilitario. Zona comercial con fácil acceso desde Av. Corrientes y Av. Scalabrini Ortiz.",
    spaceType: "Depósito",
    areaLabel: "Villa Crespo, CABA",
    approxLatLng: { lat: -34.6037, lng: -58.4388 },
    fullAddressPrivate: "Acevedo 234, CABA",
    sizeM2: 25,
    fits: ["Mercadería", "Stock comercial", "Herramientas", "Equipos"],
    accessType: "24_7",
    rulesAllowed: [
      "Mercadería comercial",
      "Acceso con vehículos medianos",
      "Múltiples visitas diarias",
    ],
    rulesNotAllowed: [
      "Productos tóxicos",
      "Armas",
      "Actividades comerciales in-situ",
    ],
    amenities: [
      "Rampa de acceso",
      "Luz incluida",
      "Alarma",
      "Baño compartido",
    ],
    priceDaily: 3500,
    priceWeekly: 21000,
    priceMonthly: 70000,
    photos: [],
    status: "active",
  },
  {
    id: "4",
    hostId: "host_2",
    createdAt: "2026-01-16T11:00:00Z",
    title: "Garage para 2 autos en Belgrano",
    description:
      "Garage espacioso para 2 autos en zona residencial de Belgrano. Excelente estado, portón eléctrico, muy seguro. A 3 cuadras de Av. Cabildo. Ideal para familias con más de un vehículo o para compartir con otro inquilino.",
    spaceType: "Garage",
    areaLabel: "Belgrano, CABA",
    approxLatLng: { lat: -34.5634, lng: -58.4545 },
    fullAddressPrivate: "Echeverría 2890, CABA",
    sizeM2: 30,
    fits: ["Auto", "SUV", "Moto"],
    accessType: "24_7",
    rulesAllowed: [
      "Hasta 2 vehículos",
      "Motocicletas adicionales",
      "Bicicletas en rincón",
    ],
    rulesNotAllowed: [
      "Vehículos utilitarios grandes",
      "Almacenamiento de combustible",
    ],
    amenities: [
      "Portón eléctrico",
      "Cámaras",
      "Iluminación automática",
      "Conexión eléctrica",
    ],
    priceDaily: 4000,
    priceWeekly: 24000,
    priceMonthly: 80000,
    photos: [],
    status: "active",
  },
  {
    id: "5",
    hostId: "host_3",
    createdAt: "2026-01-17T08:20:00Z",
    title: "Baulera pequeña en Caballito",
    description:
      "Baulera compacta de 4m² ideal para cajas y objetos personales. Edificio tranquilo con buena accesibilidad. Perfecto para mudanzas temporales o almacenamiento de pertenencias mientras viajás. Muy buena relación precio-calidad.",
    spaceType: "Baulera",
    areaLabel: "Caballito, CABA",
    approxLatLng: { lat: -34.6158, lng: -58.4394 },
    fullAddressPrivate: "Acoyte 567, CABA",
    sizeM2: 4,
    fits: ["Cajas", "Ropa", "Objetos pequeños"],
    accessType: "scheduled",
    accessHoursText: "Lun-Sáb 8-22hs",
    rulesAllowed: ["Cajas y valijas", "Ropa", "Libros y documentos"],
    rulesNotAllowed: ["Muebles grandes", "Materiales peligrosos"],
    amenities: ["Acceso controlado", "Seco", "Candado propio"],
    priceDaily: 500,
    priceMonthly: 10000,
    photos: [],
    status: "active",
  },
  {
    id: "6",
    hostId: "host_3",
    createdAt: "2026-01-18T16:45:00Z",
    title: "Cochera semicubierta en Núñez",
    description:
      "Cochera semicubierta en barrio residencial de Núñez. Techo que protege de lluvia y sol. Acceso directo desde la calle. Zona muy tranquila y segura, ideal para quienes trabajan en la zona norte o visitan el estadio regularmente.",
    spaceType: "Cochera",
    areaLabel: "Núñez, CABA",
    approxLatLng: { lat: -34.5445, lng: -58.4589 },
    fullAddressPrivate: "Crisólogo Larralde 3456, CABA",
    sizeM2: 13,
    fits: ["Auto", "Camioneta", "Moto"],
    accessType: "24_7",
    rulesAllowed: ["Vehículos particulares", "Acceso libre 24/7"],
    rulesNotAllowed: ["Vehículos de gran porte", "Almacenamiento adicional"],
    amenities: ["Techo", "Vigilancia barrial", "Acceso directo"],
    priceDaily: 2000,
    priceWeekly: 12000,
    priceMonthly: 40000,
    photos: [],
    status: "active",
  },
  {
    id: "7",
    hostId: "host_4",
    createdAt: "2026-01-19T13:10:00Z",
    title: "Depósito grande en Barracas",
    description:
      "Depósito de 40m² en zona industrial de Barracas. Altura 3.5 metros, portón amplio para carga y descarga. Ideal para distribuidoras, pequeñas industrias o emprendimientos que requieren espacio considerable. Fácil acceso desde autopistas.",
    spaceType: "Depósito",
    areaLabel: "Barracas, CABA",
    approxLatLng: { lat: -34.6481, lng: -58.3795 },
    fullAddressPrivate: "Iriarte 1890, CABA",
    sizeM2: 40,
    fits: ["Mercadería", "Maquinaria", "Stock industrial"],
    accessType: "scheduled",
    accessHoursText: "Lun-Vie 7-19hs",
    rulesAllowed: [
      "Mercadería pesada",
      "Equipamiento industrial",
      "Carga y descarga con camiones",
    ],
    rulesNotAllowed: [
      "Actividad comercial permanente",
      "Sustancias peligrosas",
    ],
    amenities: [
      "Portón amplio",
      "Conexión trifásica",
      "Baño",
      "Oficina pequeña",
    ],
    priceDaily: 5000,
    priceMonthly: 120000,
    photos: [],
    status: "active",
  },
  {
    id: "8",
    hostId: "host_4",
    createdAt: "2026-01-20T10:30:00Z",
    title: "Cochera cubierta en San Telmo",
    description:
      "Cochera cubierta en el histórico barrio de San Telmo. A pasos de la Plaza Dorrego. Ideal para turistas que visitan el barrio o trabajadores de la zona. Edificio antiguo restaurado con todas las comodidades modernas.",
    spaceType: "Cochera",
    areaLabel: "San Telmo, CABA",
    approxLatLng: { lat: -34.6214, lng: -58.3724 },
    fullAddressPrivate: "Defensa 890, CABA",
    sizeM2: 11,
    fits: ["Auto chico", "Auto mediano"],
    accessType: "24_7",
    rulesAllowed: ["Vehículos compactos", "Estacionamiento prolongado"],
    rulesNotAllowed: ["SUVs grandes", "Camionetas"],
    amenities: ["Techado completo", "Seguridad", "Portón automático"],
    priceDaily: 2800,
    priceWeekly: 17000,
    priceMonthly: 55000,
    photos: [],
    status: "active",
  },
  {
    id: "9",
    hostId: "host_5",
    createdAt: "2026-01-21T15:00:00Z",
    title: "Baulera con estanterías en Almagro",
    description:
      "Baulera de 6m² con estanterías incluidas en Almagro. Perfecto para organizar tus cosas de manera ordenada. Edificio céntrico con muy buena conectividad de transporte público. Ideal para estudiantes o profesionales.",
    spaceType: "Baulera",
    areaLabel: "Almagro, CABA",
    approxLatLng: { lat: -34.6097, lng: -58.4172 },
    fullAddressPrivate: "Medrano 567, CABA",
    sizeM2: 6,
    fits: ["Cajas", "Libros", "Objetos personales", "Ropa"],
    accessType: "scheduled",
    accessHoursText: "Todos los días 8-22hs",
    rulesAllowed: [
      "Uso de estanterías",
      "Objetos variados",
      "Acceso frecuente",
    ],
    rulesNotAllowed: ["Alimentos", "Plantas", "Mascotas"],
    amenities: ["Estanterías incluidas", "Bien iluminado", "Seguridad"],
    priceDaily: 650,
    priceWeekly: 3900,
    priceMonthly: 13000,
    photos: [],
    status: "active",
  },
  {
    id: "10",
    hostId: "host_5",
    createdAt: "2026-01-22T09:45:00Z",
    title: "Garage con taller en Villa Urquiza",
    description:
      "Garage de 35m² con espacio de taller incluido. Ideal para entusiastas del automovilismo que necesitan un lugar para guardar su auto y realizar trabajos menores. Conexión eléctrica, agua y desagüe. Zona residencial tranquila.",
    spaceType: "Garage",
    areaLabel: "Villa Urquiza, CABA",
    approxLatLng: { lat: -34.5732, lng: -58.4856 },
    fullAddressPrivate: "Monroe 4567, CABA",
    sizeM2: 35,
    fits: ["Auto", "Moto", "Herramientas", "Equipamiento de taller"],
    accessType: "24_7",
    rulesAllowed: [
      "Trabajos mecánicos menores",
      "Almacenamiento de herramientas",
      "Múltiples vehículos",
    ],
    rulesNotAllowed: [
      "Ruidos molestos nocturnos",
      "Pintura en spray",
      "Actividad comercial intensiva",
    ],
    amenities: [
      "Agua y desagüe",
      "Conexión eléctrica",
      "Mesada de trabajo",
      "Iluminación completa",
    ],
    priceDaily: 4500,
    priceWeekly: 27000,
    priceMonthly: 90000,
    photos: [],
    status: "active",
  },
];

// Mock blocked dates for availability
export const mockAvailability: AvailabilityBlock[] = [
  {
    id: "av1",
    listingId: "1",
    startDate: "2026-02-10",
    endDate: "2026-02-15",
    reason: "Reservado",
  },
  {
    id: "av2",
    listingId: "1",
    startDate: "2026-03-01",
    endDate: "2026-03-05",
    reason: "Mantenimiento",
  },
  {
    id: "av3",
    listingId: "3",
    startDate: "2026-02-20",
    endDate: "2026-02-25",
    reason: "Reservado",
  },
  {
    id: "av4",
    listingId: "5",
    startDate: "2026-02-12",
    endDate: "2026-02-18",
    reason: "Reservado",
  },
  {
    id: "av5",
    listingId: "7",
    startDate: "2026-02-08",
    endDate: "2026-02-14",
    reason: "Ocupado",
  },
];
